### ISSUE TITLE
An option should be provided to store all identity server entities within the same collection

### ISSUE THREAD

**Issue by steve-warwick** [enemaerke/IdentityServer3.DocumentDb#1]
Storing each identity server entity in it's own collection is extremely expensive. DocumentDB charges per $25 dollars a collection per month. Please add an option to store all entities with a specified collection.

**Comment by enemaerke** [comment]
Hi @steve-warwick 

Not sure I totally follow your request. Do you want an option for store the heterogeneous entities (scopes, clients and the various tokens) in the same collection?

**Comment by steve-warwick** [comment]
Yes, collections are very expensive in DocumentDB and from what I've read it sounds like the best practice is to fill one collection before creating another one.

**Comment by enemaerke** [comment]
Would you mind pasting in a few links to info on this practice? It's not something I've come across so I'll start out a little suspicious but can likely be convinced :)

**Comment by steve-warwick** [comment]
Best practice was probably not the best term. What they say is if you are concerned with costs you should start by placing as many documents in a single collection as you can. You can see this for yourself if you go to the Azure pricing calculator and start adding more and more collections. You will see the price go up fast.

**Comment by enemaerke** [comment]
I see your point. I'll require a bit of rework on my part to support mixed schemas on queries. I'll post back on this issue when I have something concrete

**Comment by enemaerke** [comment]
Hi @steve-warwick 

I've just published an updated NuGet package v.0.7.1 that by default stores everything in a single shared collection but allows for customization through the options. 

I've adjusted the various internal queries to include a 'doc_type' field to allow for shared collections and my integration test suite is working so feel free to grab the new bits, play around and send feedback (or pull requests :) )

**Comment by enemaerke** [comment]
Closing this as I've push an update implementing this to NuGet
