### ISSUE TITLE
ClientRepository

### ISSUE THREAD

**Issue by vubees** [enemaerke/IdentityServer3.DocumentDb#2]
I would like to request that a new feature for the ClientRepository where it is able to return all client documents that match a specific claim.  

Currently, I have to get all the documents first, and then filter it out from there.  The performance is hindered when working with large client document lists. 

Thank you,

**Comment by enemaerke** [comment]
@vubees I'll see if I can make time to have a quick look at such a feature. I'm not actively using this stuff right now in my dayjob so it might take a little while

**Comment by enemaerke** [comment]
@vubees as might be evident I haven't had time to do this. If you still need this I think you'll need to fork this repo or send a pull request. Sorry for not having the time to do this.

**Comment by vubees** [comment]
No worries. This is no longer needed as I made a workaround. Thank you for
responding, however.
