### ISSUE TITLE
Please add License information

### ISSUE THREAD

**Issue by Toominator** [enemaerke/IdentityServer3.DocumentDb#5]
I have used your DocumentDb implementation as a template for a DynamoDb one, which is working nicely in AWS, so thank you.
However, it has been pointed out to me that because there is no explicit license documented in your repository I probably should not be using any of your code.

Is there any chance that you might add some appropriate license, e.g. MIT or Apache ?

(It would be a great shame to have to switch back to Entity Framework and SQL Server).

**Comment by enemaerke** [comment]
Should be an MIT license now. And thanks for reaching out.
