### ISSUE TITLE
Dispose not called on IReliableReadWriteDocumentClient

### ISSUE THREAD

**Issue by durbs182** [enemaerke/IdentityServer3.DocumentDb#8]
Is there a reason you don't dispose of IReliableReadWriteDocumentClient in RepositoryBase.cs?

**Comment by enemaerke** [comment]
@durbs182 No, I guess that is an oversight. 

I'm not currently using this, so it might be a little while before I can get around to working on this. I do accept pull requests, though 😄

**Comment by durbs182** [comment]
Good I've got a fix will sort out a pull shortly
